import type { CSSProperties } from "react";

export const PERMISSIONS = [
  "Read connected tools",
  "Execute actions",
  "Access files you have approved",
  "Sync data securely",
];

export const styles: Record<string, CSSProperties> = {
  page: {
    fontFamily: 'Geist, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    maxWidth: 420,
    margin: "0 auto",
    padding: "48px 20px 40px",
    minHeight: "100vh",
    background: "#000000",
    color: "#FFFFFF",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginBottom: 28,
  },
  logoBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    background: "#111111",
    border: "1px solid #2A2A2A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  clientInitial: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "#FFFFFF",
    color: "#000000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 18,
  },
  connector: {
    width: 96,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  tileRow: {
    display: "flex",
    gap: 4,
    alignItems: "center",
  },
  successRing: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: "2px solid #22C55E",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(34, 197, 94, 0.1)",
  },
  title: {
    margin: "0 0 8px",
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    textAlign: "center",
    color: "#FFFFFF",
  },
  subtitle: {
    margin: "0 0 28px",
    fontSize: 14,
    lineHeight: 1.5,
    color: "#BDBDBD",
    textAlign: "center",
  },
  mute: {
    color: "#BDBDBD",
    fontSize: 14,
    margin: 0,
  },
  card: {
    background: "#111111",
    border: "1px solid #2A2A2A",
    borderRadius: 22,
    padding: 18,
  },
  cardTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    color: "#FFFFFF",
  },
  selectAllBtn: {
    background: "transparent",
    border: "none",
    color: "#BDBDBD",
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
    fontFamily: "inherit",
  },
  label: {
    display: "block",
    marginBottom: 14,
    fontSize: 13,
    color: "#BDBDBD",
  },
  input: {
    display: "block",
    width: "100%",
    marginTop: 6,
    padding: "11px 12px",
    borderRadius: 12,
    border: "1px solid #2A2A2A",
    background: "#000000",
    color: "#FFFFFF",
    fontSize: 14,
    boxSizing: "border-box",
    outline: "none",
  },
  checkboxList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 8,
    maxHeight: 260,
    overflowY: "auto",
  },
  wsRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 12px",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 14,
    border: "1px solid #2A2A2A",
    width: "100%",
    fontFamily: "inherit",
    color: "inherit",
  },
  box: {
    width: 20,
    height: 20,
    borderRadius: 6,
    border: "1.5px solid #2A2A2A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    marginTop: 1,
  },
  permRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    fontSize: 13,
    color: "#BDBDBD",
  },
  checkIcon: {
    color: "#FFFFFF",
    fontWeight: 700,
    fontSize: 13,
    width: 16,
    textAlign: "center",
  },
  btnPrimary: {
    width: "100%",
    padding: "13px 16px",
    borderRadius: 14,
    border: "none",
    background: "#FFFFFF",
    color: "#000000",
    fontWeight: 600,
    fontSize: 15,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  btnSecondary: {
    flex: 1,
    width: "100%",
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid #FFFFFF",
    background: "#000000",
    color: "#FFFFFF",
    fontWeight: 500,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  error: {
    color: "#f87171",
    marginTop: 16,
    fontSize: 13,
    textAlign: "center",
  },
};
